# Add (x+y)
# Sub (x-y)
# Mul(x*y)
# div(x/y) - throw an error if y=0
# StringAssign(x=y)
# Equal (x==y)
# Not Equal (x!=y)
# Greater (x>y)
# Smaller (x<y)
# Or (x || y)
# And (x&y)
# Power (x^y)
# Square (x^0.5)
# Min (x,y)
# Max (x,y)